site_name: Studio de Beleza Keuany

repo_name: "2024.1-Est-dio-de-Beleza-Keuany"
repo_url: "https://github.com/mdsreq-fga-unb/2024.1-Est-dio-de-Beleza-Keuany"

theme:
  name: material
  language: "pt"
  # favicon: docs_separados/assets/logo.png  
  # icon:
  #   logo: material/food-variant
  #   repo: fontawesome/brands/github
  
  palette:

    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  font:
    text: "Montserrat"
    code: "sans-serif"

extra_css:
  - stylesheets/styles.css

nav:
  - Introdução: index.md
  - Visão do Produto e projeto:
    - Visão do produto: visao_geral_produto/visao_produto.md
    - Visão do Projeto: visao_projeto/visao_do_projeto.md
    - Processo de Desenvolvimento: processo_desenvolvimento/processo.md

  - Reuniões: 
    - Reuniões Gerais da Equipe:
      - Ata 1 (05/10/2023): atas_reunioes_gerais/ata_1.md
      - Ata 2 (07/10/2023): atas_reunioes_gerais/ata_2.md
      - Ata 3 (12/10/2023): atas_reunioes_gerais/ata_3.md
      - Ata 4 (16/10/2023): atas_reunioes_gerais/ata_4.md
      - Ata 5 (17/10/2023): atas_reunioes_gerais/ata_5.md
      - Ata 6 (08/11/2023): atas_reunioes_gerais/ata_6.md
      - Ata 7 (10/11/2023): atas_reunioes_gerais/ata_7.md
      - Reuniões e Templates: docs_separados/reunioes_templates.md
    - Alinhamentos com Cliente:
      - Relatório de Considerações (08/10/2023): relatorios_consideracoes_cliente/relatorio-08-10-2023.md
      - Relatório de Considerações (09/11/2023): relatorios_consideracoes_cliente/relatorio-09-11-2023.md